version: '3.7'

services:
    php:
        image: rr-php:latest
        build:
            dockerfile: Dockerfile
            context: .
        working_dir: /app
        volumes:
            - .:/app
